name: movies
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  http: ^1.3.0
  shared_preferences: ^2.2.2  # ✅ Agregado para persistencia de sesión

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.OTF
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.OTF
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.OTF
          weight: 600
